database:
  - site: M1
    speed: 50
    filling: 29
    ip: 172.16.41.51
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: M2
    speed: 50
    filling: 29
    ip: 172.16.41.52
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: M3
    speed: 50
    filling: 29
    ip: 172.16.41.53
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: Q1
    speed: 50
    filling: 29
    ip: 172.16.51.51
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: Q2
    speed: 50
    filling: 29
    ip: 172.16.51.52
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: Q3
    speed: 50
    filling: 29
    ip: 172.16.51.53
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: D1
    speed: 50
    filling: 29
    ip: 172.16.32.51
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: D2
    speed: 50
    filling: 29
    ip: 172.16.32.52
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: D3
    speed: 50
    filling: 29
    ip: 172.16.32.53
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: D4
    speed: 50
    filling: 29
    ip: 172.16.32.54
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: T1
    speed: 50
    filling: 29
    ip: 192.168.100.47
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: T2
    speed: 50
    filling: 29
    ip: 192.168.100.47
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: T3
    speed: 50
    filling: 29
    ip: 192.168.100.47
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: J1
    speed: 50
    filling: 29
    ip: 172.16.21.51
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: J2
    speed: 50
    filling: 25
    ip: 172.16.21.52
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: J3
    speed: 50
    filling: 29
    ip: 172.16.21.53
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: J4
    speed: 50
    filling: 29
    ip: 172.16.21.54
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: J5
    speed: 50
    filling: 29
    ip: 172.16.21.55
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: J6
    speed: 50
    filling: 29
    ip: 172.16.21.56
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: A1
    speed: 50
    filling: 29
    ip: 192.168.62.73
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: A2
    speed: 50
    filling: 29
    ip: 192.168.62.68
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: A3
    speed: 50
    filling: 29
    ip: 192.168.62.76
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: A4
    speed: 50
    filling: 29
    ip: 192.168.62.67
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: R1
    speed: 60
    filling: 60
    ip: 172.16.11.51
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: true
  - site: R2
    speed: 60
    filling: 60
    ip: 172.16.11.52
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: true
  - site: R3
    speed: 60
    filling: 60
    ip: 172.16.11.53
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: true
  - site: R4
    speed: 50
    filling: 29
    ip: 172.16.11.54
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: R5
    speed: 60
    filling: 60
    ip: 172.16.11.55
    port: 3306
    user: root
    password: filling
    name: ccc
    use23: false
  - site: Air Compressor
    speed: 50
    filling: 29
    ip: 192.168.100.93
    port: 3306
    user: root
    password: 123456
    name: ras2021
    use23: false
